### ISSUE TITLE
ODDetection spec only checks if no wrong values were found, not that all correct values were

### ISSUE THREAD

**Issue by julkw** [CodeLionX/dODo#40]
### Describe the bug
`ocds -- expectedOCDs` is used to compare the two sets. This will return an empty set even if no ocds were found and the test will evaluate to true.

### To Reproduce
Run the ODDetectionSpec test

### Expected behavior
The sets should be tested for equality.

**Comment by SebastianSchmidl** [comment]
fixed in #42
