### ISSUE TITLE
Add Downing Protocol

### ISSUE THREAD

**Issue by julkw** [CodeLionX/dODo#50]
### Desired Solution
A node should only shutdown when all ODs etc have been found, i.e. when all nodes have nothing pending anymore. The protocol to find that out would start when a node discovers that the other nodes' workqueues are empty during workStealing.

### Alternatives?
Right now nodes shut down when they don't have anything pending and all the other nodes' workqueues are empty. This might lead to too early shutdowns however.

**Comment by SebastianSchmidl** [comment]
Related code:

https://github.com/CodeLionX/dODo/blob/d537f9e0c37100bebd09f946ee4cb456111163ec/src/main/scala/com/github/codelionx/dodo/actors/ODMaster.scala#L267-L270
