### ISSUE TITLE
Handle delayed/lost `AckWorkReceived`

### ISSUE THREAD

**Issue by julkw** [CodeLionX/dODo#51]
### Potential Problem

When sending work to another node, the sending node waits for an acknowledgement of arrival. If that doesn't arrive within 5 seconds it is assumes that the work wasn't received and it is readded to the sender's own queue. 
This leads to this work (and all work generated from these candidates) to be done twice if the work was received, but the acknowledgment message (`AckWorkReceived`) got lost or delayed.  

### Potential Solution
The work sender could resend the work instead of readding it to it's own queue. If the reason no acknowledgement was received was an overload of the system, though, this might worsen the problem. (And the receiving node would have to check received work for duplicates before adding it to its own queue)

**Comment by SebastianSchmidl** [comment]
Related code:

https://github.com/CodeLionX/dODo/blob/d537f9e0c37100bebd09f946ee4cb456111163ec/src/main/scala/com/github/codelionx/dodo/actors/ODMaster.scala#L208-L214

**Comment by SebastianSchmidl** [comment]
We can solve it with the solution discussed with Thorsten:

> - Watch actor ref of thief in sender
> - Send work over
> - If ACK received de-watch thief
> - If `Terminated` received, recover work to own queue
> - Use `akka.actor.remote.artery.transport = tcp` as transport configuration
>
> see [Meeting notes from 2019-06-25](https://github.com/CodeLionX/dODo/blob/doc/minutes/doc/minutes/2019-06-25_seminar_meeting.md#how-to-ensure-work-stealing-worked)
